import { intlLocale, translate } from "./i18n";
import type { Task } from "./types";

export type ScheduleKind = "minutes" | "hours" | "daily" | "days";

export function scheduledRunLabel(status?: NonNullable<Task["last_scheduled_run"]>["status"]) { const labels: Record<string, string> = { pending: translate("schedule.runPending"), claimed: translate("schedule.runClaimed"), session_created: translate("schedule.runSessionCreated"), running: translate("schedule.runRunning"), ambiguous: translate("schedule.runAmbiguous"), completed: translate("schedule.runCompleted"), failed: translate("schedule.runFailed"), stalled: translate("schedule.runStalled"), skipped: translate("schedule.runSkipped"), cancelled: translate("schedule.runCancelled"), aborted: translate("schedule.runAborted") }; return status ? labels[status] ?? status : translate("schedule.neverRun"); }
export function formatScheduleTime(value?: string | null) { if (!value) return translate("schedule.notCalculated"); const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat(intlLocale(), { dateStyle: "short", timeStyle: "short" }).format(date); }
export function scheduleCron(kind: ScheduleKind, interval: number, time: string, minute: number) { const [hour = 9, clockMinute = 0] = time.split(":").map(Number); if (kind === "minutes") return `*/${interval} * * * *`; if (kind === "hours") return `${minute} */${interval} * * *`; if (kind === "days") return `${clockMinute} ${hour} */${interval} * *`; return `${clockMinute} ${hour} * * *`; }
export function parseScheduleCron(cron: string): { kind: ScheduleKind; interval: number; time: string; minute: number } | null { let match = cron.match(/^\*\/(\d+) \* \* \* \*$/); if (match) return { kind: "minutes", interval: Number(match[1]), time: "09:00", minute: 0 }; match = cron.match(/^(\d+) \*\/(\d+) \* \* \*$/); if (match) return { kind: "hours", interval: Number(match[2]), time: "09:00", minute: Number(match[1]) }; match = cron.match(/^(\d+) (\d+) \*\/(\d+) \* \*$/); if (match) return { kind: "days", interval: Number(match[3]), time: `${match[2].padStart(2, "0")}:${match[1].padStart(2, "0")}`, minute: 0 }; match = cron.match(/^(\d+) (\d+) \* \* \*$/); if (match) return { kind: "daily", interval: 1, time: `${match[2].padStart(2, "0")}:${match[1].padStart(2, "0")}`, minute: 0 }; return null; }
export function describeCron(cron: string) { let match = cron.match(/^\*\/(\d+) \* \* \* \*$/); if (match) { const value = Number(match[1]); return value === 1 ? translate("schedule.everyMinute") : translate("schedule.everyMinutes", { count: value }); } match = cron.match(/^(\d+) \*\/(\d+) \* \* \*$/); if (match) { const hours = Number(match[2]); return translate(hours === 1 ? "schedule.everyHour" : "schedule.everyHours", { count: hours, minute: match[1].padStart(2, "0") }); } match = cron.match(/^(\d+) (\d+) \* \* \*$/); if (match) return translate("schedule.everyDayAt", { value0: match[2].padStart(2, "0"), value1: match[1].padStart(2, "0") }); match = cron.match(/^(\d+) (\d+) \*\/(\d+) \* \*$/); if (match) { const days = Number(match[3]); const time = `${match[2].padStart(2, "0")}:${match[1].padStart(2, "0")}`; return days === 2 ? translate("schedule.everyOtherDayAt", { value0: time }) : translate("schedule.everyDays", { count: days, time }); } return translate("schedule.customCron", { value0: cron }); }
