import { intlLocale, translate } from "./i18n";
import type { Agent, Session, Snapshot, Task } from "./types";

export function compact(value: number) { return new Intl.NumberFormat(intlLocale(), { notation: value > 9999 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value); }
export function statusOf(snapshot: Snapshot | null | undefined, sessionId: string) { const status = snapshot?.statuses[sessionId]; return status?.type ?? status?.status ?? "idle"; }
export function sessionStatus(snapshot: Snapshot | null | undefined, session: Session) { const runtime = snapshot?.statuses[session.id]; const runtimeStatus = runtime?.type ?? runtime?.status; return runtimeStatus && runtimeStatus !== "idle" ? runtimeStatus : session.control_task?.session_status ?? runtimeStatus ?? "idle"; }

export function modelIdOf(session?: Session) { const id = session?.model?.modelID ?? session?.model?.id; return id ? `${session?.model?.providerID ? `${session.model.providerID}/` : ""}${id}` : ""; }
export function modelOf(session: Session) { return modelIdOf(session) || translate("session.defaultModel"); }
export function taskSessionIds(task: Task) { return task.session_ids?.length ? task.session_ids : task.session_id ? [task.session_id] : []; }
export function sessionLifetimeTokens(session: Session) { return (session.tokens?.input ?? 0) + (session.tokens?.output ?? 0) + (session.tokens?.reasoning ?? 0); }
export function rememberedAgent(projectId: string, agents: Agent[]) { const saved = window.localStorage.getItem(`control-agent:${projectId}`) ?? ""; return agents.some((agent) => !agent.hidden && agent.mode !== "subagent" && agent.name === saved) ? saved : ""; }
export function rememberAgent(projectId: string, agent: string) { if (agent) window.localStorage.setItem(`control-agent:${projectId}`, agent); else window.localStorage.removeItem(`control-agent:${projectId}`); }
export function rememberedComposerSelection(projectId: string, agents: Agent[]) { try { const value = JSON.parse(window.localStorage.getItem(`control-composer-selection:${projectId}`) ?? "null") as unknown; if (value && typeof value === "object") { const saved = value as { agent?: unknown; model?: unknown; variant?: unknown }; const agent = typeof saved.agent === "string" && agents.some((item) => !item.hidden && item.mode !== "subagent" && item.name === saved.agent) ? saved.agent : rememberedAgent(projectId, agents); return { agent, model: typeof saved.model === "string" ? saved.model : "", variant: typeof saved.variant === "string" ? saved.variant : "" }; } } catch { /* Ignore malformed browser state. */ } return { agent: rememberedAgent(projectId, agents), model: "", variant: "" }; }
export function rememberComposerSelection(projectId: string, agent: string, model: string, variant: string) { rememberAgent(projectId, agent); window.localStorage.setItem(`control-composer-selection:${projectId}`, JSON.stringify({ agent, model, variant })); }
export function readSessionSelection(projectId: string, sessionId: string): { agent: string; model: string; variant: string } | null { try { const value = JSON.parse(window.localStorage.getItem(`control-session-selection:${projectId}:${sessionId}`) ?? "null") as unknown; return value && typeof value === "object" && typeof (value as { agent?: unknown }).agent === "string" && typeof (value as { model?: unknown }).model === "string" ? { agent: (value as { agent: string }).agent, model: (value as { model: string }).model, variant: typeof (value as { variant?: unknown }).variant === "string" ? (value as { variant: string }).variant : "" } : null; } catch { return null; } }
export function rememberSessionSelection(projectId: string, sessionId: string, agent: string, model: string, variant: string) { window.localStorage.setItem(`control-session-selection:${projectId}:${sessionId}`, JSON.stringify({ agent, model, variant })); }
export function mentionedAgents(prompt: string, agents: Agent[]) { return agents.filter((agent) => !agent.hidden && agent.mode !== "primary").filter((agent) => new RegExp(`(^|[\\s([{"'])@${agent.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?=$|[\\s.,!?;:)}\\]"'])`, "u").test(prompt)).map((agent) => agent.name); }
export function selectedDefaultModel(snapshot?: Snapshot | null) { const session = [...(snapshot?.sessions ?? [])].filter((item) => !item.parentID && (item.model?.modelID || item.model?.id)).sort((left, right) => (right.time?.updated ?? 0) - (left.time?.updated ?? 0))[0]; return session ? modelOf(session) : undefined; }
export function slashCommand(value: string) { const match = value.trim().match(/^\/([a-z0-9][a-z0-9_-]{0,63})(?:\s+([\s\S]*))?$/u); return match ? { name: match[1], arguments: match[2] ?? "" } : null; }
export function relativeTime(value?: number) { if (!value) return translate("common.timeUnknown"); const milliseconds = value > 100_000_000_000 ? value : value * 1000; const minutes = Math.max(0, Math.floor((Date.now() - milliseconds) / 60000)); if (minutes < 1) return translate("common.justNow"); const locale = intlLocale(); if (minutes < 60) return new Intl.RelativeTimeFormat(locale, { numeric: "auto" }).format(-minutes, "minute"); if (minutes < 1440) return new Intl.RelativeTimeFormat(locale, { numeric: "auto" }).format(-Math.floor(minutes / 60), "hour"); return new Intl.RelativeTimeFormat(locale, { numeric: "auto" }).format(-Math.floor(minutes / 1440), "day"); }
export function absoluteDateTime(value?: number) { if (!value) return translate("common.timeUnknown"); const milliseconds = value > 100_000_000_000 ? value : value * 1000; return new Intl.DateTimeFormat(intlLocale(), { dateStyle: "medium", timeStyle: "medium" }).format(milliseconds); }
export function clockTime(value?: number) { if (!value) return ""; const milliseconds = value > 100_000_000_000 ? value : value * 1000; return new Intl.DateTimeFormat(intlLocale(), { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(milliseconds); }
export function sessionDuration(session: Session) { const start = session.time?.created; const end = session.time?.updated; if (!start || !end || end < start) return null; const milliseconds = (end > 100_000_000_000 ? end : end * 1000) - (start > 100_000_000_000 ? start : start * 1000); const seconds = Math.max(0, Math.floor(milliseconds / 1000)); if (seconds < 60) return translate("session.format.seconds", { value0: seconds }); const minutes = Math.floor(seconds / 60); const rest = seconds % 60; if (minutes < 60) return translate("session.format.minutesSeconds", { value0: minutes, value1: String(rest).padStart(2, "0") }); const hours = Math.floor(minutes / 60); return translate("session.format.hoursMinutes", { value0: hours, value1: String(minutes % 60).padStart(2, "0") }); }
